import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  metadata.title =
    "Florcita Nails - Servicios de manicura y academia en Buenos Aires";
  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="description"
          content="Florcita Nails no es solo un salón de belleza, ¡es un estudio de uñas y una academia!"
        />
        <meta
          property="og:title"
          content="Florcita Nails - Servicios de manicura y academia en Buenos Aires"
        />
        <meta
          property="og:description"
          content="Florcita Nails no es solo un salón de belleza, ¡es un estudio de uñas y una academia!"
        />
        <meta
          property="og:image"
          content="https://www.florcitanails.com.ar/logo.png"
        />
        <meta property="og:type" content="website" />
        <meta name="og:url" content="https://www.florcitanails.com.ar/" />
        <link rel="canonical" href="https://florcitanails.com.ar/" />
      </head>
      <body className={`${poppins && poppins.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
